# -*- coding: utf-8 -*-
"""NGrams-Fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoNiRrZaL6uGxe848V6gwn0oC0D_toTN

N-gram Analysis for the Fibonacci Series
=========================================
Covers:
  1. Generating the Fibonacci sequence
  2. Building n-grams (unigrams, bigrams, trigrams, 4-grams)
  3. Predicting the next term from a given n-gram window
  4. Interactive Demo
"""

from ipywidgets import interact, IntSlider, IntText, VBox, HBox, Label, Button, Output
from IPython.display import display, HTML, clear_output

# ── USER INPUTS ────────────────────────────────────────────────
fib = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]

gram_input = IntText(
    value=3,
    description="N-gram Size:",
    style={"description_width": "100px"},
    layout={"width": "200px"}
)

len_input = IntText(
    value=len(fib),
    description="Seq Length:",
    style={"description_width": "100px"},
    layout={"width": "200px"}
)

apply_btn = Button(
    description="✅ Apply Settings",
    button_style="info",
    layout={"width": "200px"}
)

out = Output()

# ── MAIN DISPLAY FUNCTION ──────────────────────────────────────
def show_window(pos, window_size, sequence):

    gram_names = {1: "Unigram", 2: "Bigram", 3: "Trigram",
                  4: "4-gram",  5: "5-gram", 6: "6-gram"}
    gram_label = gram_names.get(window_size, f"{window_size}-gram")

    html = """
    <div style="
        background: linear-gradient(135deg, #0f172a, #1e293b);
        padding: 20px;
        border-radius: 20px;
        color: white;
        font-family: Arial;
    ">
    <h2 style='color:#38bdf8'>Fibonacci Sliding Window Explorer 🚀</h2>
    """

    # ── STATUS BAR ────────────────────────────────────────────
    html += f"""
    <div style="display:flex; gap:12px; margin-bottom:20px; flex-wrap:wrap;">
        <div style="background:#1e3a5f; padding:10px 18px; border-radius:12px; border:2px solid #38bdf8;">
            <div style="color:#94a3b8; font-size:11px;">N-GRAM TYPE</div>
            <div style="color:#38bdf8; font-size:18px; font-weight:bold;">{gram_label} (N={window_size})</div>
        </div>
        <div style="background:#3b2700; padding:10px 18px; border-radius:12px; border:2px solid #f59e0b;">
            <div style="color:#94a3b8; font-size:11px;">CURRENT POSITION</div>
            <div style="color:#f59e0b; font-size:18px; font-weight:bold;">Index {pos} of {len(sequence) - window_size}</div>
        </div>
        <div style="background:#2d1b69; padding:10px 18px; border-radius:12px; border:2px solid #a78bfa;">
            <div style="color:#94a3b8; font-size:11px;">SEQUENCE LENGTH</div>
            <div style="color:#a78bfa; font-size:18px; font-weight:bold;">{len(sequence)} numbers</div>
        </div>
        <div style="background:#14532d; padding:10px 18px; border-radius:12px; border:2px solid #34d399;">
            <div style="color:#94a3b8; font-size:11px;">WINDOWS AVAILABLE</div>
            <div style="color:#34d399; font-size:18px; font-weight:bold;">{len(sequence) - window_size + 1} total</div>
        </div>
    </div>
    """

    # ── SEQUENCE DISPLAY ───────────────────────────────────────
    html += "<div style='margin:20px 0;'>"
    for i, num in enumerate(sequence):
        if pos <= i < pos + window_size:
            color  = "#f59e0b"
            border = "3px solid #fbbf24"
        else:
            color  = "#334155"
            border = "2px solid #475569"

        fsize = "18px" if num > 999 else "22px"
        arrow = "<div style='font-size:10px;color:#fbbf24;text-align:center;'>▼</div>" if i == pos else "<div style='height:16px'></div>"

        html += f"""
        <span style="display:inline-block; text-align:center; margin:4px;">
            {arrow}
            <span style="
                display:inline-block;
                width:60px; height:60px; line-height:60px; text-align:center;
                background:{color}; border-radius:12px; border:{border};
                font-size:{fsize}; font-weight:bold;
            ">{num}</span>
            <div style='font-size:10px; color:#475569; text-align:center;'>[{i}]</div>
        </span>
        """
    html += "</div>"

    # ── CURRENT WINDOW ─────────────────────────────────────────
    window = sequence[pos : pos + window_size]
    html += f"""
    <div style="background:#1e293b; padding:15px; border-radius:15px; margin-top:10px;">
        <h3 style="margin:0 0 8px 0;">Current {gram_label} Window</h3>
        <h1 style='color:#fbbf24; margin:0;'>{tuple(window)}</h1>
    </div>
    """

    # ── PREDICTION ─────────────────────────────────────────────
    prediction = window[-1] + window[-2]
    html += f"""
    <div style="background:#0f766e; padding:15px; border-radius:15px; margin-top:15px;">
        <h3 style="margin:0 0 8px 0;">🔮 Prediction (next number)</h3>
        <h1 style="margin:0;">{prediction}</h1>
        <p style="margin:8px 0 0 0;">{window[-2]} + {window[-1]} = {prediction}</p>
    </div>
    """

    html += "</div>"
    display(HTML(html))


# ── APPLY BUTTON WITH VALIDATION ──────────────────────────────
def on_apply(btn):
    out.clear_output(wait=True)

    n       = gram_input.value
    seq_len = len_input.value

    errors = []   # collect all error messages

    # ── VALIDATION RULES ──────────────────────────────────────
    if n < 1:
        errors.append("❌ N-gram size must be at least <b>1</b>")

    if n > 6:                                          # 👈 MAX 6
        errors.append(f"❌ N-gram size <b>{n}</b> exceeds max allowed: <b>6</b> &nbsp;→ please enter 1–6")

    if seq_len < 3:
        errors.append("❌ Sequence length must be at least <b>3</b>")

    if seq_len > 20:                                   # 👈 MAX 20
        errors.append(f"❌ Sequence length <b>{seq_len}</b> exceeds max allowed: <b>20</b> &nbsp;→ please enter 3–20")

    if not errors and seq_len <= n:                    # seq must be longer than window
        errors.append(f"❌ Sequence length <b>{seq_len}</b> must be greater than N-gram size <b>{n}</b>")

    # ── SHOW ERRORS IF ANY ────────────────────────────────────
    if errors:
        error_html = """
        <div style="
            background: #450a0a;
            border: 2px solid #ef4444;
            border-radius: 14px;
            padding: 16px 20px;
            font-family: Arial;
            margin-top: 10px;
        ">
            <div style="color:#ef4444; font-size:16px; font-weight:bold; margin-bottom:10px;">
                ⚠️ Invalid Input — Please Fix:
            </div>
        """
        for msg in errors:
            error_html += f"<div style='color:#fca5a5; margin:6px 0; font-size:14px;'>• {msg}</div>"

        error_html += """
            <div style="
                color:#94a3b8; font-size:12px; margin-top:14px;
                border-top:1px solid #7f1d1d; padding-top:10px;
            ">
                ✅ Valid ranges: &nbsp; N-gram = 1 to 6 &nbsp;|&nbsp; Sequence length = 3 to 20
            </div>
        </div>
        """
        with out:
            display(HTML(error_html))
        return   # 🛑 STOP — don't run the visualizer

    # ── ALL VALID → BUILD AND SHOW ────────────────────────────
    new_fib = [1, 1]
    while len(new_fib) < seq_len:
        new_fib.append(new_fib[-1] + new_fib[-2])
    new_fib = new_fib[:seq_len]

    with out:
        interact(
            lambda pos: show_window(pos, n, new_fib),
            pos=IntSlider(
                min=0,
                max=len(new_fib) - n,
                value=0,
                description="Slide ▶",
                style={"description_width": "70px"},
                layout={"width": "500px"}
            )
        )

apply_btn.on_click(on_apply)

# ── LAYOUT ────────────────────────────────────────────────────
controls = HBox([
    VBox([Label("① N-gram size (max 6):"),       gram_input]),
    VBox([Label("② Sequence length (max 20):"),  len_input]),
    VBox([Label("③ Click to apply:"),             apply_btn]),
])

display(controls, out)
on_apply(None)

from ipywidgets import interact, IntSlider, IntText, VBox, HBox, Label, Button, Output
from IPython.display import display, HTML, clear_output

# ── USER INPUTS ────────────────────────────────────────────────
fib = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]

# Widget: N-gram size input
gram_input = IntText(
    value=3,
    description="N-gram Size:",
    style={"description_width": "100px"},
    layout={"width": "200px"}
)

# Widget: Sequence length input
len_input = IntText(
    value=len(fib),
    description="Seq Length:",
    style={"description_width": "100px"},
    layout={"width": "200px"}
)

# Apply button
apply_btn = Button(
    description="✅ Apply Settings",
    button_style="info",
    layout={"width": "200px"}
)

# Output area
out = Output()

# ── MAIN DISPLAY FUNCTION ──────────────────────────────────────
def show_window(pos, window_size, sequence):

    gram_names = {1: "Unigram", 2: "Bigram", 3: "Trigram",
                  4: "4-gram",  5: "5-gram", 6: "6-gram"}
    gram_label = gram_names.get(window_size, f"{window_size}-gram")

    html = """
    <div style="
        background: linear-gradient(135deg, #0f172a, #1e293b);
        padding: 20px;
        border-radius: 20px;
        color: white;
        font-family: Arial;
    ">
    <h2 style='color:#38bdf8'>Fibonacci Sliding Window Explorer 🚀</h2>
    """

    # ── STATUS BAR (3 new things) ──────────────────────────────
    html += f"""
    <div style="
        display: flex;
        gap: 12px;
        margin-bottom: 20px;
        flex-wrap: wrap;
    ">
        <div style="background:#1e3a5f; padding:10px 18px; border-radius:12px; border:2px solid #38bdf8;">
            <div style="color:#94a3b8; font-size:11px;">N-GRAM TYPE</div>
            <div style="color:#38bdf8; font-size:18px; font-weight:bold;">{gram_label} (N={window_size})</div>
        </div>
        <div style="background:#3b2700; padding:10px 18px; border-radius:12px; border:2px solid #f59e0b;">
            <div style="color:#94a3b8; font-size:11px;">CURRENT POSITION</div>
            <div style="color:#f59e0b; font-size:18px; font-weight:bold;">Index {pos} of {len(sequence) - window_size}</div>
        </div>
        <div style="background:#2d1b69; padding:10px 18px; border-radius:12px; border:2px solid #a78bfa;">
            <div style="color:#94a3b8; font-size:11px;">SEQUENCE LENGTH</div>
            <div style="color:#a78bfa; font-size:18px; font-weight:bold;">{len(sequence)} numbers</div>
        </div>
        <div style="background:#14532d; padding:10px 18px; border-radius:12px; border:2px solid #34d399;">
            <div style="color:#94a3b8; font-size:11px;">WINDOWS AVAILABLE</div>
            <div style="color:#34d399; font-size:18px; font-weight:bold;">{len(sequence) - window_size + 1} total</div>
        </div>
    </div>
    """

    # ── SEQUENCE DISPLAY ───────────────────────────────────────
    html += "<div style='margin:20px 0;'>"

    for i, num in enumerate(sequence):
        if pos <= i < pos + window_size:
            color  = "#f59e0b"
            border = "3px solid #fbbf24"
            fsize  = "18px" if num > 999 else "22px"
        else:
            color  = "#334155"
            border = "2px solid #475569"
            fsize  = "18px" if num > 999 else "22px"

        # Mark window start
        arrow = "<div style='font-size:10px;color:#fbbf24;text-align:center;'>▼</div>" if i == pos else "<div style='height:16px'></div>"

        html += f"""
        <span style="display:inline-block; text-align:center; margin:4px;">
            {arrow}
            <span style="
                display:inline-block;
                width:60px; height:60px; line-height:60px;
                text-align:center;
                background:{color};
                border-radius:12px;
                border:{border};
                font-size:{fsize};
                font-weight:bold;
            ">{num}</span>
            <div style='font-size:10px; color:#475569; text-align:center;'>[{i}]</div>
        </span>
        """

    html += "</div>"

    # ── CURRENT WINDOW ─────────────────────────────────────────
    window = sequence[pos : pos + window_size]

    html += f"""
    <div style="background:#1e293b; padding:15px; border-radius:15px; margin-top:10px;">
        <h3 style="margin:0 0 8px 0;">Current {gram_label} Window</h3>
        <h1 style='color:#fbbf24; margin:0;'>{tuple(window)}</h1>
    </div>
    """

    # ── PREDICTION ─────────────────────────────────────────────
    prediction = window[-1] + window[-2]

    html += f"""
    <div style="background:#0f766e; padding:15px; border-radius:15px; margin-top:15px;">
        <h3 style="margin:0 0 8px 0;">🔮 Prediction (next number)</h3>
        <h1 style="margin:0;">{prediction}</h1>
        <p style="margin:8px 0 0 0;">{window[-2]} + {window[-1]} = {prediction}</p>
    </div>
    """

    html += "</div>"
    display(HTML(html))


# ── APPLY BUTTON LOGIC ─────────────────────────────────────────
def on_apply(btn):
    out.clear_output(wait=True)

    n   = max(2, min(6, gram_input.value))   # clamp 2–6
    seq_len = max(n + 1, min(20, len_input.value))  # must be > window size

    new_fib = [1, 1]
    while len(new_fib) < seq_len:
        new_fib.append(new_fib[-1] + new_fib[-2])
    new_fib = new_fib[:seq_len]

    with out:
        interact(
            lambda pos: show_window(pos, n, new_fib),
            pos=IntSlider(
                min=0,
                max=len(new_fib) - n,
                value=0,
                description="Slide ▶",
                style={"description_width": "70px"},
                layout={"width": "500px"}
            )
        )

apply_btn.on_click(on_apply)

# ── INITIAL LAYOUT ─────────────────────────────────────────────
controls = HBox([
    VBox([Label("① Choose N-gram type:"),  gram_input]),
    VBox([Label("② Choose sequence length:"), len_input]),
    VBox([Label("③ Click to apply:"), apply_btn]),
])

display(controls, out)
on_apply(None)   # run once on load with defaults

#Generating Fibonacci Series

def fibonacci (n):
  a,b = 0, 1
  fibonacci_series = [0 , 1]

  while a < n :
    fibonacci_series.append(a + b)
    a, b = b , a + b


  return fibonacci_series

fibonacci_series = fibonacci(100)
print(fibonacci_series)

# Building n-grams (unigrams, bigrams, trigrams, 4-grams)
def make_ngrams(words, n):
  ngrams = []

  for i in range(len(words)):
    gram = tuple(words[i : i+n])
    if len(gram) == n:
      ngrams.append(gram)

  return ngrams

bigrams = make_ngrams(fibonacci_series, 2)
trigrams = make_ngrams(fibonacci_series, 3)

print("Bigrams of Fibonacci Series are: ", bigrams)
print("Trigrams of Fibonacci Series are: ", trigrams)

# Predict the next term from a given n-gram window

def predict_next(current_num, grams):

  for gram in grams:
    if gram[0] == current_num:
        return gram[1]

  return -1


print(predict_next(8, trigrams))